security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
pcss:
  host: http://127.0.0.1/
  adobe-host: http://127.0.0.1/
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  oracle-host: http://127.0.0.1/
  oracle-name: oracle
  generic-agent-id: 1
  generic-part-id: 1


