security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
pcss:
  host: ${ORDS_HOST}
  adobe-host: ${ADOBE_HOST}
  oracle-host: ${ORACLE_HOST}
  oracle-name: ${ORACLE_NAME}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

