security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
pcss:
  host: http://127.0.0.1/
  adobe-host: http://127.0.0.1/
  oracle-host: http://127.0.0.1/
  oracle-name: oracle
  generic-agent-id: ${GENERIC_AGEN_ID}
  generic-part-id: 1

