security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
pcss:
  host: ${ORDS_HOST}
  namespace: ${PCSS_NAMESPACE}
  oracle-host: ${ORACLE_HOST}
  oracle-name: ${ORACLE_NAME}
  adobe-host: ${ADOBE_HOST}
management:
  trace:
    http:
      include: TIME_TAKEN,RESPONSE_HEADERS
  endpoints:
    web:
      exposure:
        include: httptrace,metrics,prometheus,health

